[package]
name = "fuzzy-message-detection"
version = "0.1.0"
edition = "2021"

[dependencies]
# curve25519-dalek = {version = "4.1.3", default-features = false, features = ["digest", "rand_core"]}
rand_core = { version = "0.6", default-features = false }
sha3 = { version = "0.9", default-features = false }
subtle = {  version = "2.5"}
rand_chacha = { version = "0.3", default-features = false }
curve25519-dalek = { package = "curve25519-dalek-ng", version = "4.1", default-features = false, features = ["u64_backend"] }
