[package]
name = "fuzzy-message-detection"
version = "0.1.0"
edition = "2021"

[dependencies]
curve25519-dalek = {version = "4.1.3", default-features = false, features = ["digest", "rand_core", "serde"]}
rand_core = { version = "0.6", default-features = false, features = ["getrandom"] }
serde = { version = "1.0.217", features = ["derive"] }
sha2 = "0.10.8"
