name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  fmt-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Check code formatting
      run: cargo fmt --check

  clippy-no-std:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Clippy (no_std)
      run: cargo clippy --verbose
    - name: Clippy (no_std + serde)
      run: cargo clippy --verbose --features serde

  clippy-with-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Clippy (with tests)
      run: cargo clippy --verbose --tests
    - name: Clippy (with tests + serde)
      run: cargo clippy --verbose --tests --features serde

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run tests
      run: cargo test --verbose

  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Generate docs
      run: cargo doc --verbose
